// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;


namespace Tank_Wiki_React_ASP_App.Server.Models;

public partial class Nation
{
    [Key]
    public int NationId { get; set; }

    [Required]
    public string NationName { get; set; }

    // Внешний ключ на Picture
    public int? PictureId { get; set; }

    // Навигационное свойство
    public Picture Picture { get; set; }
    //[InverseProperty("Nation")]
    //public virtual ICollection<Tank> Tanks { get; set; } = new List<Tank>();
    public List<Tank> Tanks { get; set; } = [];

}