// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Tank_Wiki_React_ASP_App.Server.Models;

public partial class Nation
{
    [Key]
    public int NationId { get; set; }

    [Required]
    public string NationName { get; set; }

    [InverseProperty("Nation")]
    public virtual ICollection<Tank> Tanks { get; set; } = new List<Tank>();
}