// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Tank_Wiki_React_ASP_App.Server.Models;

public partial class TankType
{
    [Key]
    public int TankTypeId { get; set; }

    [Required]
    public string TypeMachine { get; set; }

    //[InverseProperty("Type")]
    //public virtual ICollection<Tank> Tanks { get; set; } = new List<Tank>();
    public List<Tank> Tanks { get; set; } = [];
}