// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Tank_Wiki_React_ASP_App.Server.Models;

public partial class Armor
{
    [Key]
    public int ArmorId { get; set; }

    public int HullFront { get; set; }

    public int HullSide { get; set; }

    public int HullRear { get; set; }

    public int? TankId { get; set; }

    [Required]
    public string Name { get; set; }

    [ForeignKey("TankId")]
    [InverseProperty("Armor")]
    public virtual Tank Tank { get; set; }
}