// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Tank_Wiki_React_ASP_App.Server.Models.ModelsManyToMany;

namespace Tank_Wiki_React_ASP_App.Server.Models;

public partial class Gun
{
    [Key]
    public int GunId { get; set; }

    public int Tier { get; set; }

    [Required]
    public string Name { get; set; }

    public int Penetration { get; set; }

    public int Damage { get; set; }

    public double RateOfFire { get; set; }

    public double Accuracy { get; set; }

    public double AimTime { get; set; }

    public double Weight { get; set; }

    public int Ammunition { get; set; }

    public long Price { get; set; }

    //[ForeignKey("GunId")]
    //[InverseProperty("Guns")]
    //public virtual ICollection<Turret> Turrets { get; set; } = new List<Turret>();
    public List<TurretGun> TurretGuns { get; set; } = [];// Связь многие ко многим
}