// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Tank_Wiki_React_ASP_App.Server.Models.ModelsManyToMany;

namespace Tank_Wiki_React_ASP_App.Server.Models;

public partial class Suspension
{
    [Key]
    public int SuspensionId { get; set; }

    public int Tier { get; set; }

    [Required]
    public string Name { get; set; }

    public double LoadLimit { get; set; }

    public int TraverseSpeed { get; set; }

    public double Weight { get; set; }

    public long Price { get; set; }

    //[ForeignKey("SuspensionId")]
    //[InverseProperty("Suspensions")]
    //public virtual ICollection<Tank> Tanks { get; set; } = new List<Tank>();
    public List<TankSuspension> TankSuspensions { get; set; }
}