// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Tank_Wiki_React_ASP_App.Server.Models;

[Index("NationId", Name = "IX_Tanks_NationId")]
[Index("TypeId", Name = "IX_Tanks_TypeId")]
public partial class Tank
{
    [Key]
    public int TankId { get; set; }

    [Required]
    public string Name { get; set; }

    public int Tier { get; set; }

    public int HitPoints { get; set; }

    public bool Status { get; set; }

    public long Price { get; set; }

    public string Description { get; set; }

    public int TypeId { get; set; }

    public int ArmorId { get; set; }

    [Required]
    public string Crew { get; set; }

    public int NationId { get; set; }

    [InverseProperty("Tank")]
    public virtual Armor Armor { get; set; }

    [ForeignKey("NationId")]
    [InverseProperty("Tanks")]
    public virtual Nation Nation { get; set; }

    [ForeignKey("TypeId")]
    [InverseProperty("Tanks")]
    public virtual TankType Type { get; set; }

    [ForeignKey("TankId")]
    [InverseProperty("Tanks")]
    public virtual ICollection<Engine> Engines { get; set; } = new List<Engine>();

    [ForeignKey("TankId")]
    [InverseProperty("Tanks")]
    public virtual ICollection<Radio> Radios { get; set; } = new List<Radio>();

    [ForeignKey("TankId")]
    [InverseProperty("Tanks")]
    public virtual ICollection<Suspension> Suspensions { get; set; } = new List<Suspension>();

    [ForeignKey("TankId")]
    [InverseProperty("Tanks")]
    public virtual ICollection<Turret> Turrets { get; set; } = new List<Turret>();
}