// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Tank_Wiki_React_ASP_App.Server.Models;

public partial class Turret
{
    [Key]
    public int TurretId { get; set; }

    [Required]
    public string TurretName { get; set; }

    public int Tier { get; set; }

    public int TurretFront { get; set; }

    public int TurretSide { get; set; }

    public int TurretRear { get; set; }

    public double Turn { get; set; }

    public int Overview { get; set; }

    public long Price { get; set; }

    public int Weight { get; set; }

    [ForeignKey("TurretId")]
    [InverseProperty("Turrets")]
    public virtual ICollection<Gun> Guns { get; set; } = new List<Gun>();

    [ForeignKey("TurretId")]
    [InverseProperty("Turrets")]
    public virtual ICollection<Tank> Tanks { get; set; } = new List<Tank>();
}